package com.chernowii.camcontrol.camera.goproAPI.model

import com.google.gson.annotations.SerializedName

data class GPStatusResponse  (
        @SerializedName("status") val status: Status,
        @SerializedName("settings") val settings: Settings
)

/*
 * TODO: status.39 is unclear as it has 2 descritpions:
 *  https://github.com/watchingJu/goprowifihack/blob/master/HERO4/CameraStatus.md
 * Ms == multishot
 */
    data class Status(
            @SerializedName("1") val intBatteryAvailable: Int,
            @SerializedName("2") val intBatteryLevel: Int,
            @SerializedName("3") val unknown_03: Int,
            @SerializedName("4") val unknown_04: Int,
            @SerializedName("6") val unknown_06: Int,
            @SerializedName("8") val recordingStatus: Int,
            @SerializedName("9") val unknown_09: Int,
            @SerializedName("10") val unknown_10: Int,
            @SerializedName("11") val unknown_11: Int,
            @SerializedName("13") val currentRecordingVideoDuration: Int,
            @SerializedName("14") val unknown_14: Int,
            @SerializedName("15") val unknown_15: Int,
            @SerializedName("16") val unknown_16: Int,
            @SerializedName("17") val unknown_17: Int,
            @SerializedName("19") val unknown_19: Int,
            @SerializedName("20") val unknown_20: Int,
            @SerializedName("21") val unknown_21: Int,
            @SerializedName("22") val unknown_22: Int,
            @SerializedName("23") val unknown_23: Int,
            @SerializedName("24") val unknown_24: Int,
            @SerializedName("26") val unknown_26: Int,
            @SerializedName("27") val unknown_27: Int,
            @SerializedName("28") val unknown_28: Int,
            @SerializedName("29") val unknown_29: Int,
            @SerializedName("30") val unknown_30: Int,
            @SerializedName("31") val numberOfClientsConnected: Int,
            @SerializedName("32") val streamingFeedStatus: Int,
            @SerializedName("33") val sdCardInserted: Int,
            @SerializedName("34") val remainingPhotos: Int,
            @SerializedName("35") val remainingVideoTime: Int,
            @SerializedName("36") val numberOfBatchPhotosTaken: Int,
            @SerializedName("37") val numberOfVideosShot: Int,
            @SerializedName("38") val numberOfAllPhotosTaken: Int,
            @SerializedName("39") val numberOfAllVideosTaken: Int,
            @SerializedName("40") val unknown_40: Int,
            @SerializedName("41") val unknown_41: Int,
            @SerializedName("42") val unknown_42: Int,
            @SerializedName("43") val currentMode: Int,
            @SerializedName("44") val currentSubMode: Int,
            @SerializedName("45") val unknown_45: Int,
            @SerializedName("46") val unknown_46: Int,
            @SerializedName("47") val unknown_47: Int,
            @SerializedName("48") val unknown_48: Int,
            @SerializedName("49") val unknown_49: Int,
            @SerializedName("54") val remainingFreeSpace: Int,
            @SerializedName("55") val unknown_55: Int,
            @SerializedName("56") val unknown_56: Int,
            @SerializedName("57") val unknown_57: Int,
            @SerializedName("58") val unknown_58: Int,
            @SerializedName("59") val unknown_59: Int
    )

    data class Settings (
            @SerializedName("1") val unknown_01: Int,
            @SerializedName("2") val videoResolution: Int,
            @SerializedName("3") val frameRate: Int,
            @SerializedName("4") val fovVideo: Int,
            @SerializedName("5") val timelapsVideoInterval: Int,
            @SerializedName("6") val loopingVideoInterval: Int,
            @SerializedName("7") val photoVideoInterval: Int,
            @SerializedName("8") val lowLight: Int,
            @SerializedName("9") val spotMeterVideo: Int,
            @SerializedName("10") val protuneVideo: Int,
            @SerializedName("11") val whiteBalanceVideo: Int,
            @SerializedName("12") val colorVideo: Int,
            @SerializedName("13") val isoLimitVideo: Int,
            @SerializedName("14") val sharpnessVideo: Int,
            @SerializedName("15") val evCompVideo: Int,
            @SerializedName("16") val unknown_16: Int,
            @SerializedName("17") val megapixelsPhoto: Int,
            @SerializedName("18") val continousMode: Int,
            @SerializedName("19") val shutter: Int,
            @SerializedName("20") val spotMeterPhoto: Int,
            @SerializedName("21") val protunePhoto: Int,
            @SerializedName("22") val whiteBalancePhoto: Int,
            @SerializedName("23") val colorPhoto: Int,
            @SerializedName("24") val isoLimitPhoto: Int,
            @SerializedName("25") val sharpnessPhoto: Int,
            @SerializedName("26") val evCompPhoto: Int,
            @SerializedName("27") val defaultMultishotSubMode: Int,
            @SerializedName("28") val megapixelsMs: Int,
            @SerializedName("29") val burstRateMs: Int,
            @SerializedName("30") val timelapsIntervalMs: Int,
            @SerializedName("31") val nightShutterExposureMs: Int,
            @SerializedName("32") val nightlapsIntervalMs: Int,
            @SerializedName("33") val spotMeterMs: Int,
            @SerializedName("34") val protuneMs: Int,
            @SerializedName("35") val whiteBalanceMs: Int,
            @SerializedName("36") val colorMs: Int,
            @SerializedName("37") val isoLimitMs: Int,
            @SerializedName("38") val sharpnessMs: Int,
            @SerializedName("39") val evCompMs: Int,
            @SerializedName("40") val unknown_40: Int,
            @SerializedName("41") val unknown_41: Int,
            @SerializedName("42") val unknown_42: Int,
            @SerializedName("43") val unknown_43: Int,
            @SerializedName("44") val unknown_44: Int,
            @SerializedName("45") val unknown_45: Int,
            @SerializedName("46") val unknown_46: Int,
            @SerializedName("47") val unknown_47: Int,
            @SerializedName("48") val unknown_48: Int,
            @SerializedName("49") val lcdBrightness: Int,
            @SerializedName("50") val lcdLock: Int,
            @SerializedName("51") val lcdTimeoutSleep: Int,
            @SerializedName("52") val orientation: Int,
            @SerializedName("53") val defaultBootMode: Int,
            @SerializedName("54") val quickCapture: Int,
            @SerializedName("55") val ledStatus: Int,
            @SerializedName("56") val volumeBeeps: Int,
            @SerializedName("57") val videoFormat: Int,
            @SerializedName("58") val onScreenData: Int,
            @SerializedName("59") val autoPowerOff: Int,
            @SerializedName("60") val unknown_60: Int,
            @SerializedName("61") val unknown_61: Int,
            @SerializedName("62") val unknown_62: Int,
            @SerializedName("63") val unknown_63: Int,
            @SerializedName("64") val unknown_64: Int,
            @SerializedName("65") val unknown_65: Int,
            @SerializedName("66") val unknown_66: Int,
            @SerializedName("67") val unknown_67: Int,
            @SerializedName("68") val currentVideoSubMode: Int,
            @SerializedName("69") val photoSubMode: Int,
            @SerializedName("70") val multishotSubMode: Int,
            @SerializedName("71") val unknown_71: Int,
            @SerializedName("72") val lcdDisplay: Int
            // @SerializedName("73") val manualExposure: Int
            // @SerializedName("74") val isoMode: Int
            // @SerializedName("75") val isoMinPhoto: Int
            // @SerializedName("76") val isoMinMs: Int
    )